version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: rxmen_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rxmen_bot
      MYSQL_USER: rxmen_user
      MYSQL_PASSWORD: rxmen_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
